<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="5" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_20_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_20_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_20_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_25_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_25_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_25_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_27_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_27_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_27_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_30_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_30_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_30_IST_2020.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_33_IST_2020.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jun_07_22_33_33_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_33_IST_2020.jpg height=200 width=200></a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Test" duration-ms="15767" started-at="2020-06-07T17:03:17Z" finished-at="2020-06-07T17:03:33Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="2868" started-at="2020-06-07T17:03:17Z" finished-at="2020-06-07T17:03:20Z">
      <class name="testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:testcases.BankManagerLoginTest@f736069]" name="loginTest" duration-ms="2406" started-at="2020-06-07T17:03:17Z" finished-at="2020-06-07T17:03:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Bank Manager Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Bank Manager Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.BankManagerLoginTest.loginTest(BankManagerLoginTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_20_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_20_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_20_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="9238" started-at="2020-06-07T17:03:21Z" finished-at="2020-06-07T17:03:30Z">
      <class name="testcases.AddCustomerTest">
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@2c35e847]" name="addCustomerTest" duration-ms="3418" started-at="2020-06-07T17:03:21Z" data-provider="dp" finished-at="2020-06-07T17:03:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rahul]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Arora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A234234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_25_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_25_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_25_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@2c35e847]" name="addCustomerTest" duration-ms="2270" started-at="2020-06-07T17:03:25Z" data-provider="dp" finished-at="2020-06-07T17:03:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Arora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A24324]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_27_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_27_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_27_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="FAIL" signature="addCustomerTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@2c35e847]" name="addCustomerTest" duration-ms="2416" started-at="2020-06-07T17:03:28Z" data-provider="dp" finished-at="2020-06-07T17:03:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Cory]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Paul]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[E34343]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_30_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_30_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_30_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
      </class> <!-- testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
    <test name="Open Account Test" duration-ms="2785" started-at="2020-06-07T17:03:30Z" finished-at="2020-06-07T17:03:33Z">
      <class name="testcases.OpenAccountTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.OpenAccountTest@306e95ec]" name="setUp" is-config="true" duration-ms="8175" started-at="2020-06-07T17:03:09Z" finished-at="2020-06-07T17:03:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="openAccountTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.OpenAccountTest@306e95ec]" name="openAccountTest" duration-ms="2444" started-at="2020-06-07T17:03:30Z" data-provider="dp" finished-at="2020-06-07T17:03:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Rahul Arora]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rupee]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Open Account Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Open Account Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.OpenAccountTest.openAccountTest(OpenAccountTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_33_IST_2020.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jun_07_22_33_33_IST_2020.jpg target="_blank"><img src=Sun_Jun_07_22_33_33_IST_2020.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- openAccountTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.OpenAccountTest@306e95ec]" name="tearDown" is-config="true" duration-ms="663" started-at="2020-06-07T17:03:33Z" finished-at="2020-06-07T17:03:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.OpenAccountTest -->
    </test> <!-- Open Account Test -->
  </suite> <!-- Data Driven Test -->
</testng-results>
